### ISSUE TITLE
Install on Ruby 2.6?

### ISSUE THREAD

**Issue by Crell** [AskalotCQA/askalot#14]
I am trying to install Askalot on a Ruby 2.6 cloud instance.  When I run bundle install, though, I get the following error:

```
        Post-install message from paperclip:
        ##################################################
        #  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
        ##################################################
        
        Paperclip is now compatible with aws-sdk >= 2.0.0.
        
        If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
        changes:
        
        * You must set the `s3_region`
        * If you are explicitly setting permissions anywhere, such as in an initializer,
          note that the format of the permissions changed from using an underscore to
          using a hyphen. For example, `:public_read` needs to be changed to
          `public-read`.
        
        For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
        http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
        W: /app/.global/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
        W: rake aborted!
        W: NoMethodError: undefined method `[]' for nil:NilClass
        W: /app/config/application.rb:19:in `env_type'
        W: /app/config/application.rb:40:in `<top (required)>'
        W: /app/Rakefile:4:in `require'
        W: /app/Rakefile:4:in `<top (required)>'
        W: /app/.global/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
        W: /app/.global/bin/bundle:23:in `load'
        W: /app/.global/bin/bundle:23:in `<main>'
        W: (See full trace by running task with --trace)
```

I'm a developer but not in Ruby, so I'm not entirely sure how to correct this.  It appears to be a version issue with outdated code in a dependency, but I don't know how easy that is to resolve.  It doesn't look like one of the current dependabot issues that have been filed.

**Comment by Crell** [comment]
Hm, never mind.  It was a different command to install assets that seems to have been the issue, which isn't in the docs after all so I removed it.
